(ns kirke.spec.common
  (:require [clojure.spec.alpha :as spec]))

(spec/def ::string? string?)
(spec/def ::map? map?)
(spec/def ::id string?)
(spec/def ::has-id (spec/keys :req-un [::id]))
(spec/def ::url string?)
(spec/def ::username string?)
(spec/def ::password string?)
(spec/def ::location (spec/keys :req-un [::url] :opt-un [::username ::password]))
(spec/def ::locations (spec/every (spec/or :file-url-task string? :database ::location) :kind vector?))
(spec/def ::async? boolean?)
(spec/def ::input (spec/keys :req-un [::locations]))
(spec/def ::output ::input)
(spec/def ::operation (spec/or ::string? ::map?))
(spec/def ::type #(contains? #{"reader" "writer" "custom"} %))
(spec/def ::task (spec/keys :req-un [::has-id] :opt-un [::type ::input ::operation ::output]))
(spec/def ::tasks (spec/every ::task :kind vector?))
(spec/def ::pipeline (spec/keys :req-un [::has-id] :opt-un [::tasks]))
(spec/def ::pipelines (spec/every ::pipeline :kind vector?))
